service: todo-ddd

provider:
  name: aws
  region: eu-west-2
  runtime: provided.al2
  lambdaHashingVersion: 20201221

functions:
  http:
    handler: public/index.php
    layers:
      - ${bref:layer.php-81-fpm}
    events:
      - httpApi: '*'

package:
  exclude:
    - 'tests/**'

plugins:
  - ./vendor/bref/bref
