version: '3'

tasks:
  composer:
    desc: Run Composer, the dependency manager for PHP.
    cmds:
      - |
        docker run --rm --interactive --tty \
        --env COMPOSER_HOME \
        --env COMPOSER_CACHE_DIR \
        --volume ${COMPOSER_HOME:-$HOME/.config/composer}:$COMPOSER_HOME \
        --volume ${COMPOSER_CACHE_DIR:-$HOME/.cache/composer}:$COMPOSER_CACHE_DIR \
        --volume $PWD:/app \
        composer {{.CLI_ARGS}}
    silent: true
