version: '3'

tasks:
  composer:
    desc: Run Composer, the dependency manager for PHP
    cmds:
      - |
        docker run --rm --interactive --tty \
        --env COMPOSER_HOME=/root/.config/composer \
        --env COMPOSER_CACHE_DIR=/root/.cache/composer \
        --volume ${COMPOSER_HOME:-$HOME/.config/composer}:/root/.config/composer \
        --volume ${COMPOSER_CACHE_DIR:-$HOME/.cache/composer}:/root/.cache/composer \
        --volume $PWD:/app \
        composer {{.CLI_ARGS}}
    silent: true

  deploy:
    desc: Deploy to AWS
    cmds:
      - serverless deploy

  up:
    desc: Start the local development environment
    cmds:
      - docker-compose up

  psalm:
    desc: Run Psalm, a static analysis tool for PHP
    cmds:
      - docker-compose run --rm --entrypoint /var/task/vendor/bin/psalm php
